server:
  port: 8080
springdoc:
  show-actuator: true
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true
    path: /swagger-doc/v3/api-docs
  cache:
    disabled: true
  show-login-endpoint: true
spring:
  security:
    token:
      expiresInMinutes: 20
      issuer: GK
      secret: IS5IobIItq0pRX9JL9TvdQ40Oa93u2Wojlign4V3L30
  r2dbc:
    url:  r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
    timeouts:
      customer-list: 5
      customer: 6
      user: 3

logging:
  level:
    root: debug
