server:
  port: 8071
springdoc:
  show-actuator: true
  api-docs:
    groups:
      enabled: true
spring:
  security:
    token:
      expiresInMinutes: 5
      issuer: GK
      secret: IS5IobIItq0pRX9JL9TvdQ40Oa93u2Wojlign4V3L30
  r2dbc:
    url:  r2dbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    url: jdbc:postgresql://db:5432/postgres
    user: postgres
    password: postgres
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    root: INFO
