version: '3.4'
services:
  db1:
    image: postgres:latest
    container_name: Postgres_local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  redis1:
    image: redis
    container_name: redis-local
    ports:
      - "6379:6379"
volumes:
  postgres_db:

